# Basic Jekyll configuration
title: "Secret Lab Notes"
tagline: "Explorations in Decentralized Organic Computing & Quantum Technologies"
description: "Lab journal entries on the intersection of organic computing, quantum tech, and planetary defense systems"
baseurl: ""
url: "https://prashantbhaga.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
theme: minima # We'll customize this with our lab notes styling

# Include posts from submodule
include:
  - posts

# Lab notes custom styling (we'll use these variables in our CSS)
lab_notes_style:
  font: "monospace"
  color_scheme: "dark"
  date_format: "Lab Entry #%j, %Y-%m-%d"

# Process files without front matter
optional_front_matter:
  remove_originals: false

# Process markdown files with no front matter
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Add a markdown processor to handle rendering
markdown_ext: "markdown,md"

# Enable direct markdown rendering
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "posts"
    values:
      layout: "post"
